### ISSUE TITLE
Fix `make tag` workflow

### ISSUE THREAD

**Issue by jamescooke** [jamescooke/flake8-aaa#224]
## Current behaviour

`make tag` fails in default dev environment on py310 as a result of _not_ having `asttokens` installed:

```
git tag -a $(python -c 'from src.flake8_aaa.__about__ import __version__; print("v{}".format(__version__))')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/james/active/flake8-aaa/src/flake8_aaa/__init__.py", line 1, in <module>
    from .checker import Checker
  File "/home/james/active/flake8-aaa/src/flake8_aaa/checker.py", line 5, in <module>
    import asttokens
ModuleNotFoundError: No module named 'asttokens'
```

## Expected behaviour

Fix `make tag` so the release process is easy again.

**Comment by jamescooke** [comment]
Fixed in #233
